# Gemfile

source 'https://rubygems.org'

gem 'rails', '~> 7.0'
gem 'net-http-persistent'
gem 'json'
gem 'dotenv-rails', groups: [:development, :test]

# Vous pouvez aussi ajouter des gems pour des outils comme Webpacker ou TailwindCSS
gem 'webpacker'
gem 'tailwindcss-rails'